apiVersion: servapi.dev-state.com/v1alpha1
kind: Tfserv
metadata:
  name: tfserv-sample
spec:
  #Name is the name of the model
  name: "tfserv-test"
  #Version is the model version
  #Version: 1538687457
  #Replicas is the number of pod replicas
  replicas: 3
  #GrpcPort is the port number listening RPC
  grpcPort: 9000
  #RestPort is the port number listening REST
  restPort: 8500
  #ConfigMap is the name of the ConfigMap used for configuration
  configMap: "tf-serving-models-config"
  #ConfigFileName is the name of the config file
  configFileName: "configFile"
  #ConfigFileLocation is the path to config file
  configFileLocation: "/var/config"
  #SecretFileName is the name of the secret file
  secretFileName: "tf-secret"
  #SecretFileLocation is the path to the Secret file
  secretFileLocation: "/secret/gcp-credentials/"
