apiVersion: v1
kind: ConfigMap
metadata:
  name: tf-serving-models-config
data:
  models.conf: |+
    model_config_list: {
      config: {
        name: "resnet",
        base_path: "gs://tfmodel-store",
        model_platform: "tensorflow",
        model_version_policy: {
          specific: {
            versions: 1538687457
          }
        }
      }
    }