apiVersion: servapi.dev-state.com/v1alpha1
kind: Tfserv
metadata:
  name: tfserv-sample
spec:
  #GrpcPort is the port number listening RPC
  grpcPort: 9000
  #RestPort is the port number listening REST
  restPort: 8500
  #Replicas is the number of pod replicas
  replicas: 3
  #ConfigMap is the name of the ConfigMap used for configuration
  configMap: "tf-serving-models-config"
  #ConfigFileName is the name of the config file
  configFileName: "models.conf"
  #ConfigFileLocation is the path to config file
  configFileLocation: "/var/config/"
  #SecretFileName is the name of the secret file
  secretFileName: "gcp-secret-tfserv.json"
  #SecretFileLocation is the path to the Secret file
  secretFileLocation: "/secret/gcp-credentials/"
